version: '2'

services:
  kafka:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: kafka
    ports:
      - 2181:2181
      - 3030:3030
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 9092:9092
